"""增加时间信息

Revision ID: 1791499b5d10
Revises: e04ed2119f01
Create Date: 2025-04-13 10:20:44.770496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1791499b5d10'
down_revision: Union[str, None] = 'e04ed2119f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('articles', sa.Column('update_time', sa.DateTime(), nullable=False))
    op.add_column('folders', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('folders', sa.Column('update_time', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('notes', sa.Column('update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'update_time')
    op.drop_column('notes', 'create_time')
    op.drop_column('folders', 'update_time')
    op.drop_column('folders', 'create_time')
    op.drop_column('articles', 'update_time')
    op.drop_column('articles', 'create_time')
    # ### end Alembic commands ###
