"""definition of all entity and relation

Revision ID: 1bf7c40393d4
Revises: 56ae02842433
Create Date: 2025-04-10 10:44:24.487467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf7c40393d4'
down_revision: Union[str, None] = '56ae02842433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articlenotes',
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.Column('noteid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('noteid')
    )
    op.create_index(op.f('ix_articlenotes_noteid'), 'articlenotes', ['noteid'], unique=False)
    op.create_table('articlesetarticles',
    sa.Column('articlesetid', sa.Integer(), nullable=True),
    sa.Column('articleid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('articleid')
    )
    op.create_index(op.f('ix_articlesetarticles_articleid'), 'articlesetarticles', ['articleid'], unique=False)
    op.create_table('articletags',
    sa.Column('articleid', sa.Integer(), nullable=True),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('tagid')
    )
    op.create_index(op.f('ix_articletags_tagid'), 'articletags', ['tagid'], unique=False)
    op.create_table('grouparticlesets',
    sa.Column('groupid', sa.Integer(), nullable=True),
    sa.Column('articlesetid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('articlesetid')
    )
    op.create_index(op.f('ix_grouparticlesets_articlesetid'), 'grouparticlesets', ['articlesetid'], unique=False)
    op.create_table('userarticlesets',
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('articlesetid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('articlesetid')
    )
    op.create_index(op.f('ix_userarticlesets_articlesetid'), 'userarticlesets', ['articlesetid'], unique=False)
    op.create_table('usergroups',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('groupid', sa.Integer(), nullable=False),
    sa.Column('isadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('userid', 'groupid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usergroups')
    op.drop_index(op.f('ix_userarticlesets_articlesetid'), table_name='userarticlesets')
    op.drop_table('userarticlesets')
    op.drop_index(op.f('ix_grouparticlesets_articlesetid'), table_name='grouparticlesets')
    op.drop_table('grouparticlesets')
    op.drop_index(op.f('ix_articletags_tagid'), table_name='articletags')
    op.drop_table('articletags')
    op.drop_index(op.f('ix_articlesetarticles_articleid'), table_name='articlesetarticles')
    op.drop_table('articlesetarticles')
    op.drop_index(op.f('ix_articlenotes_noteid'), table_name='articlenotes')
    op.drop_table('articlenotes')
    # ### end Alembic commands ###
