"""增加时间信息2

Revision ID: 4df692d79c60
Revises: 1791499b5d10
Create Date: 2025-04-13 10:25:25.139263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4df692d79c60'
down_revision: Union[str, None] = '1791499b5d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('groups', sa.Column('update_time', sa.DateTime(), nullable=False))
    op.add_column('tags', sa.Column('create_time', sa.DateTime(), nullable=False))
    op.add_column('tags', sa.Column('update_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'update_time')
    op.drop_column('tags', 'create_time')
    op.drop_column('groups', 'update_time')
    op.drop_column('groups', 'create_time')
    # ### end Alembic commands ###
