"""definition of all entity

Revision ID: 56ae02842433
Revises: c976ca5c1d8f
Create Date: 2025-04-10 00:04:27.588283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56ae02842433'
down_revision: Union[str, None] = 'c976ca5c1d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=30), nullable=False))
    op.drop_index('ix_users_teacher_name', table_name='users')
    op.drop_index('ix_users_work_number', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_column('users', 'teacher_name')
    op.drop_column('users', 'work_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('work_number', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('teacher_name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_work_number', 'users', ['work_number'], unique=False)
    op.create_index('ix_users_teacher_name', 'users', ['teacher_name'], unique=False)
    op.drop_column('users', 'username')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
