"""添加数据库实体关系定义

Revision ID: 5dc79cf05715
Revises: 1bf7c40393d4
Create Date: 2025-04-11 20:59:07.250741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5dc79cf05715'
down_revision: Union[str, None] = '1bf7c40393d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('groups_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['groups_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_id'), 'folders', ['id'], unique=False)
    op.create_table('user_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.drop_index('ix_articlesetarticles_articleid', table_name='articlesetarticles')
    op.drop_table('articlesetarticles')
    op.drop_index('ix_articletags_tagid', table_name='articletags')
    op.drop_table('articletags')
    op.drop_index('ix_userarticlesets_articlesetid', table_name='userarticlesets')
    op.drop_table('userarticlesets')
    op.drop_index('ix_grouparticlesets_articlesetid', table_name='grouparticlesets')
    op.drop_table('grouparticlesets')
    op.drop_index('ix_articlesets_id', table_name='articlesets')
    op.drop_table('articlesets')
    op.drop_index('ix_articlenotes_noteid', table_name='articlenotes')
    op.drop_table('articlenotes')
    op.drop_table('usergroups')
    op.add_column('articles', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'folders', ['folder_id'], ['id'])
    op.add_column('notes', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'articles', ['article_id'], ['id'])
    op.add_column('tags', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'articles', ['article_id'], ['id'])
    op.add_column('users', sa.Column('avatar', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'article_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'article_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'folder_id')
    op.create_table('usergroups',
    sa.Column('userid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('groupid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isadmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('userid', 'groupid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('articlenotes',
    sa.Column('articleid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('noteid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('noteid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_articlenotes_noteid', 'articlenotes', ['noteid'], unique=False)
    op.create_table('articlesets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_articlesets_id', 'articlesets', ['id'], unique=False)
    op.create_table('grouparticlesets',
    sa.Column('groupid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('articlesetid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('articlesetid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_grouparticlesets_articlesetid', 'grouparticlesets', ['articlesetid'], unique=False)
    op.create_table('userarticlesets',
    sa.Column('userid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('articlesetid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('articlesetid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_userarticlesets_articlesetid', 'userarticlesets', ['articlesetid'], unique=False)
    op.create_table('articletags',
    sa.Column('articleid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tagid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('tagid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_articletags_tagid', 'articletags', ['tagid'], unique=False)
    op.create_table('articlesetarticles',
    sa.Column('articlesetid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('articleid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('articleid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_articlesetarticles_articleid', 'articlesetarticles', ['articleid'], unique=False)
    op.drop_table('user_group')
    op.drop_index(op.f('ix_folders_id'), table_name='folders')
    op.drop_table('folders')
    # ### end Alembic commands ###
