"""fix：更改password名

Revision ID: 9af9d4a35bef
Revises: c49010e96150
Create Date: 2025-04-12 10:27:52.832186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9af9d4a35bef'
down_revision: Union[str, None] = 'c49010e96150'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=60), nullable=False))
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', mysql.VARCHAR(length=60), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
