"""添加数据库实体关系定义

Revision ID: b7940480e6e6
Revises: 5dc79cf05715
Create Date: 2025-04-11 21:10:47.613089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b7940480e6e6'
down_revision: Union[str, None] = '5dc79cf05715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_user_group_folder', 'folders', ['user_id', 'group_id'])
    op.drop_constraint('folders_ibfk_1', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'groups', ['group_id'], ['id'])
    op.drop_column('folders', 'groups_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('groups_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_ibfk_1', 'folders', 'groups', ['groups_id'], ['id'])
    op.drop_constraint('uq_user_group_folder', 'folders', type_='unique')
    op.drop_column('folders', 'group_id')
    # ### end Alembic commands ###
