"""fix 数据库定义

Revision ID: c49010e96150
Revises: 2acf0b902f73
Create Date: 2025-04-12 10:19:29.708681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c49010e96150'
down_revision: Union[str, None] = '2acf0b902f73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content', sa.String(length=255), nullable=True))
    op.drop_column('notes', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('name', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('notes', 'content')
    # ### end Alembic commands ###
