"""使用远程数据库

Revision ID: c976ca5c1d8f
Revises: 5c562ce917d3
Create Date: 2025-04-09 21:33:43.133516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c976ca5c1d8f'
down_revision: Union[str, None] = '5c562ce917d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_number', sa.Integer(), nullable=False),
    sa.Column('hash_password', sa.String(length=60), nullable=False),
    sa.Column('teacher_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_teacher_name'), 'users', ['teacher_name'], unique=False)
    op.create_index(op.f('ix_users_work_number'), 'users', ['work_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_work_number'), table_name='users')
    op.drop_index(op.f('ix_users_teacher_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
